CREATE DATABASE TEST_SEDC
GO


CREATE TABLE TableA (Id int NOT NULL);
CREATE TABLE Tableb (Id int NOT NULL);
INSERT INTO TableA VALUES (1), (2);
INSERT INTO Tableb VALUES (2), (3);

SELECT * FROM TableA CROSS JOIN Tableb;